import { Platform, Pressable, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ChevronLeft } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

function Section({ title, children }: { title: string; children: string }) {
  return (
    <View className="gap-1.5">
      <Text className="font-sans-semibold text-sm text-zinc-800">{title}</Text>
      <Text className="font-sans text-xs leading-5 text-zinc-600">{children}</Text>
    </View>
  );
}

export default function PrivacyPolicyPage() {
  const router = useRouter();

  return (
    <SafeAreaView className="flex-1 bg-app-bg" edges={[]}>
      <ScrollView className="flex-1" contentContainerStyle={{ paddingHorizontal: 24, paddingTop: Platform.OS === 'web' ? 32 : 12, paddingBottom: 48 }}>
        <View className="w-full max-w-[720px] self-center">
          <Pressable onPress={() => router.back()} className="mb-4 flex-row items-center gap-1 self-start active:opacity-70">
            <ChevronLeft size={16} color="#3b82f6" />
            <Text className="font-sans-medium text-sm text-blue-500">Back</Text>
          </Pressable>

          <Text className="mb-1 font-sans-bold text-2xl text-zinc-900">Privacy Policy</Text>
          <Text className="mb-6 font-sans text-xs text-zinc-400">Last updated: April 12, 2026</Text>

          <View className="gap-5">
            <Section title="Overview">
              Arc Radius is an LGBTQ+ legislative tracking platform built by students at UC Berkeley. We are deeply committed to protecting user privacy — especially for LGBTQ+ youth in vulnerable environments. This policy explains what data we collect (very little) and how we handle it.
            </Section>

            <Section title="Data We Do Not Collect">
              We do not collect, store, or sell personal information for general use of Arc Radius. We do not require account creation or login to browse bills, search, or use the Ask feature. We do not track your location, IP address, or browsing history. We do not use cookies for tracking or advertising purposes.
            </Section>

            <Section title="Misclassification Reports (Optional)">
              If you choose to report a bill misclassification, you will be asked to sign in with Google. This is solely to prevent abuse of the reporting system. We only receive your display name and email address from Google — no other account data is accessed. Report data (your name, email, and the report itself) is stored only for the purpose of reviewing classification accuracy. You are never required to sign in to use any other part of Arc Radius.
            </Section>

            <Section title="Anonymous Usage">
              All searches, bill lookups, and interactions with the Ask feature are anonymous. We do not log queries in a way that can be tied back to any individual user. There is no user profile, no session tracking, and no analytics that identify you.
            </Section>

            <Section title="Third-Party Services">
              Arc Radius uses AWS infrastructure (Lambda, Bedrock, SageMaker) to process legislative data and power our knowledge graph. These services process bill data — not user data. The Ask feature sends your query text to generate an answer, but queries are not stored or linked to any user identity. We use Neo4j Aura as our graph database to store legislative data only.
            </Section>

            <Section title="Crisis Resources">
              Our crisis resources page links to external organizations (The Trevor Project, Trans Lifeline, 988 Lifeline, etc.). When you tap these links, you leave Arc Radius. We encourage you to review the privacy policies of those organizations. We do not share any data with these services.
            </Section>

            <Section title="Data Sources">
              Legislative data displayed in Arc Radius comes from publicly available sources: LegiScan (bill tracking API), ACLU legislation tracker, and Plural (TrackBill). Classification labels are generated by our machine learning models. All data is about public legislation, not about users.
            </Section>

            <Section title="Children's Privacy">
              Arc Radius does not knowingly collect any personal information from anyone, including children under 13. Since we collect no personal data, there is no children's data to protect — but we want to be explicit: this app is safe for users of all ages.
            </Section>

            <Section title="Changes to This Policy">
              We may update this privacy policy as the platform evolves. Any changes will be reflected on this page with an updated date. Since we collect no user data, changes will likely relate to new data sources or third-party services.
            </Section>

            <Section title="Contact">
              If you have questions about this privacy policy, please reach out to us at arcradius.org or through our GitHub repository.
            </Section>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
