import { Platform, Pressable, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ChevronLeft } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

function Section({ title, children }: { title: string; children: string }) {
  return (
    <View className="gap-1.5">
      <Text className="font-sans-semibold text-sm text-zinc-800">{title}</Text>
      <Text className="font-sans text-xs leading-5 text-zinc-600">{children}</Text>
    </View>
  );
}

export default function TermsOfServicePage() {
  const router = useRouter();

  return (
    <SafeAreaView className="flex-1 bg-app-bg" edges={[]}>
      <ScrollView className="flex-1" contentContainerStyle={{ paddingHorizontal: 24, paddingTop: Platform.OS === 'web' ? 32 : 12, paddingBottom: 48 }}>
        <View className="w-full max-w-[720px] self-center">
          <Pressable onPress={() => router.back()} className="mb-4 flex-row items-center gap-1 self-start active:opacity-70">
            <ChevronLeft size={16} color="#3b82f6" />
            <Text className="font-sans-medium text-sm text-blue-500">Back</Text>
          </Pressable>

          <Text className="mb-1 font-sans-bold text-2xl text-zinc-900">Terms of Service</Text>
          <Text className="mb-6 font-sans text-xs text-zinc-400">Last updated: April 12, 2026</Text>

          <View className="gap-5">
            <Section title="Acceptance of Terms">
              By using Arc Radius, you agree to these terms. Arc Radius is a free, open-source platform built as a capstone project at UC Berkeley's School of Information (MIDS program). It is provided as-is for informational and educational purposes.
            </Section>

            <Section title="Purpose">
              Arc Radius is an LGBTQ+ legislative tracking tool that helps users understand the policy landscape across US states. It aggregates publicly available legislative data and uses machine learning to classify bills as supportive or harmful to LGBTQ+ rights. It is not a legal service and does not provide legal advice.
            </Section>

            <Section title="No Legal Advice">
              Nothing on Arc Radius constitutes legal advice. Bill classifications (supportive, harmful) are generated by machine learning models and may not be accurate. Always consult a qualified attorney or legal aid organization for legal guidance. The crisis resources and legal aid links we provide are for informational purposes only.
            </Section>

            <Section title="Accuracy of Information">
              We strive to keep legislative data accurate and up to date, but we cannot guarantee completeness or accuracy. Bill data comes from LegiScan, ACLU, and Plural — any delays or errors in those sources may be reflected in Arc Radius. AI-generated summaries and classifications should be verified against official sources.
            </Section>

            <Section title="User Conduct">
              You agree to use Arc Radius for lawful purposes only. You may not attempt to disrupt, overload, or interfere with the platform's services. You may not scrape or bulk-download data from Arc Radius in a way that degrades service for other users.
            </Section>

            <Section title="Misclassification Reports">
              Submitting a misclassification report requires signing in with Google to prevent abuse. By signing in, you consent to Arc Radius receiving your Google display name and email address for the sole purpose of processing your report. Reports are reviewed to improve classification accuracy. Submitting false or spam reports may result in your reports being disregarded.
            </Section>

            <Section title="Intellectual Property">
              Arc Radius is an open-source project. The source code is available on GitHub. Legislative data displayed is from public sources. The Arc Radius name, logo, and original design are the property of the Arc Radius team.
            </Section>

            <Section title="Third-Party Links">
              Arc Radius contains links to external organizations and resources (crisis hotlines, legal aid services, state legislatures). We are not responsible for the content, privacy practices, or availability of these external sites.
            </Section>

            <Section title="Limitation of Liability">
              Arc Radius is provided "as is" without warranties of any kind. The Arc Radius team, UC Berkeley, and its contributors are not liable for any damages arising from the use of this platform. This includes but is not limited to reliance on bill classifications, AI-generated content, or external resource links.
            </Section>

            <Section title="Changes to Terms">
              We may update these terms as the platform evolves. Continued use of Arc Radius after changes constitutes acceptance of the updated terms.
            </Section>

            <Section title="Contact">
              For questions about these terms, reach out to us at arcradius.org or through our GitHub repository.
            </Section>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
